### ISSUE TITLE
Android実機にて installation に登録されない

### ISSUE THREAD

**Issue by xenophy** [NIFCloud-mbaas/ncmb_unity#112]
SDKの改善にご協力いただきありがとうございます。  
(Thank you for your support our SDK.)

SDKの不具合を報告する場合は、以下の項目を確認してください。  
(If you want to report a bug of the SDK, please confirm the following terms.)

- サンプルコードにAPIキーや個人情報が含まれていないか (The sample code does not include credential information?)
- 同じバグをすでに誰かが報告していてOpenになっているissueはないか (This bug is not being reported?)

## 不具合の概要(Description of bug)
iOS実機、Unity Editorは正常に動作しております。
Android実機において、検証を行い動作しないため、ご連絡いたします。
SenderId、AndroidManifest.xmlの設定はもちろん行っております。

NCMBのC#スクリプトを追いかけたところ

NCMBPush.cs
```
m_AJClass.CallStatic("InitSenderId", senderId);
```

の呼び出しまで実行されておりますが、
NCMBManager.onTokenReceived に返ってきてないようです。

なので、installationに登録される、**installation.SaveAsync** 以前に
このイベントハンドラの呼び出しが行われていないようです。

**InitSenderId**の内部まで追いかけられなかったため、
不具合に関する解消に関してアップデートを待てば良いのか、
他の原因があるのか等ご教授いただきたく連絡しました。

よろしくお願いいたします。

- SDKのバージョン(SDK version)
v3.2.1

Android SDK : API 27
Android NDK : android-ndk-r13b
Java : jdk1.8.0_144

- 不具合が発生した環境(Environment requirement)
Unity 2017.3.1.f1

- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
クイックスタートにある手順通り

- エラーメッセージ(Error messages)
特になし

**Comment by xenophy** [comment]
補足：
v3.1.1 にダウングレードしてみましたが、現象は同じでした。

**Comment by xenophy** [comment]
その後、aar側もデバッグしながら原因を調べてみたところ

GCMInit.checkPlayServices にて false が返ってきているため、
RegistrationIntentServiceが実行できていないことがわかりました。

checkPlayServices内で、GoogleApiAvailability.isGooglePlayServicesAvailableを行っているところで、
SERVICE_VERSION_UPDATE_REQUIRED (int値 = 2)が返ってきています。

まだ解決はしていないのですが、おそらく手元の「Google Play開発者ツール」のバージョンが古いために発生している現象ではないかと思い検証を進めております。

NCMB Unity SDK を利用していると、
「GooglePlay開発者サービスが古いのでバージョンアップしてください」的なダイアログ表示を
出す術がないのですが、今後ここら辺の対応は可能でしょうか。（希望）

取り急ぎ、現状SDK本体というよりも、環境によるものなので先にご報告いたしました。

**Comment by xenophy** [comment]
報告：Google開発者サービスを更新することで、デバイストークンの取得が動きました。

**Comment by ncmbadmin** [comment]
お世話になっております、issueをいただき、ありがとうございました。
本件、すでにご連絡いただいた「Google開発者サービスを更新することで、デバイストークンの取得が動きました。」とのことで解決されたかと思いますので、issueをクローズさせていただきます。
フィードバックいただき、ありがとうございます。
同様の事象となるユーザも想定されるため、コミュニティなどにTIPとして共有させていただきます。ご了承ください。

今後とも、mobile backend どうぞよろしくお願いいたします。
