### ISSUE TITLE
【要望】WaitForSecondsをWaitForSecondsRealtimeに変更

### ISSUE THREAD

**Issue by am1tanaka** [NIFCLOUD-mbaas/ncmb_unity#120]
# 要望内容
NCMBConnections.csのSendRequest()メソッド内で、処理の完了をWaitForSeconds()で待っていますが、WaitForSecondsRealtime()への変更を要望いたします。

# 理由
WaitForSeconds()はスケールされた時間で待ってしまうため、Time.timeScaleを変更すると待ち時間が変化してしまいます。Time.timeScaleが0の場合、止まってしまいます。

ご検討、よろしくお願いいたします。

# 参考
- https://docs.unity3d.com/ja/current/ScriptReference/WaitForSecondsRealtime.html

**Comment by wagomu** [comment]
ゲームのリザルト画面の実装でTimeScaleを0にしており、
同じ問題にぶつかったので検証しました。
NCMBConnection.cs : 411 行目の WaitForSeconds を WaitForSecondsRealTime にするだけで、この問題が解決することを確認できています。

**Comment by ncmbadmin** [comment]
お世話になっております。本件ですが、
https://github.com/NIFCLOUD-mbaas/ncmb_unity/releases/tag/v4.4.2
こちらのバージョンにて対応いたしますので、ご確認ください。
今後ともどうぞよろしくお願いします。
