### ISSUE TITLE
アプリのプロセスが切れている状態でリッチプッシュ通知を起動するとWebViewが表示されない

### ISSUE THREAD

**Issue by ncmbsdk** [NIFCloud-mbaas/ncmb_unity#15]

**Comment by ncmbadmin** [comment]
* 以下の手順で再現確認いたしましたが、Unity SDK (v. 4.0.1)で再現されないことを確認いたしましたので、本issueをクローズいたします。
1) プッシュできるアプリをビルドする
2) Android端末にAPKをインストールする
3) アプリを起動して、Foregroundの状態にする
4) 登録されたトークンにリッチプッシュ通知を送信する
5) 届けたプッシュ通知をクリックする
6) Webviewは問題なく表示される
