### ISSUE TITLE
V4.0.2/新規サインインしてもアカウント情報を取得できない

### ISSUE THREAD

**Issue by rise696** [NIFCloud-mbaas/ncmb_unity#157]
## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version)v4.0.2
- 不具合が発生した環境(Environment requirement)Unity2019.2.6f1+windows10
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
ニフクラのサンプル「アプリにログイン機能をつけよう！」にNCMB4.0.2をインポートする

**Comment by ncmbadmin** [comment]
お世話になっております、issueをいただき、ありがとうございます。

順次、内容を確認し優先付けをおこなったうえで対応いたしますので、
今しばらくお待ちいただきますようお願いいたします。
対応次第、こちらの issue にて報告いたします。

今後とも、mobile backend どうぞよろしくお願いいたします。

**Comment by ncmbadmin** [comment]
ご連絡ありがとうございます。
以下の検証を実施いたしましたが、お客様と同様な現象を再現できませんでした。
お手数かけますが、再度ご確認いただけますと幸いです。

■検証詳細

https://github.com/NIFCloud-mbaas/UnityLoginApp
最新版のSDK(4.0.2)を適用することで、データの取得をすることが出来ました。
手順を記載いたしましたので、ご確認の程お願いいたします。
​

## 手順
1. 4.0.2のSDKを以下からinstall
　https://github.com/NIFCloud-mbaas/ncmb_unity/releases
2. unityへimport
3. 元のAssets配下のNCMBとPluginsを2のものに差し替え
4. NCMBSettingオブジェクトの中にNCMBSetting.csをドロップ
5. 実行しサインインしLoginsignin.csの`void Start()`に以下のユーザー検索のコードをペーストする
https://mbaas.nifcloud.com/doc/current/user/basic_usage_unity.html#%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E6%A4%9C%E7%B4%A2
6. コード内の`query.WhereEqualTo ("userName", "Yamada Tarou");`
　"Yamada Tarou"をサインインした名前に適当に変更する
7. mBaaS側の会員のaclのパーミッションを会員から全員へ変更する

## 結果
Unityで検索が実行され、成功時の処理が実行されました。

また、aclの設定をしていない場合は、
処理は成功しますが、結果が空で取得されます。

**Comment by rise696** [comment]
すみませんが、ユーザー検索機能は「List<NCMBUser>」の部分でエラーを吐いてしまうので実行できません

**Comment by kobayashi-masaya** [comment]
お世話になっております。
List<NCMBUser>にエラーが出てしまう場合、

`using System.Collections.Generic;`

上記を定義する必要があるかと思います。
ご確認のほどよろしくお願い致します。

**Comment by ncmbadmin** [comment]
お世話になっております。
ご確認いただき、ありがとうございます。
具体的なエラーの記載がなかったので、原因の特定が難しいですが、
考えられる原因としては、例えば、Listにエラーが出てしまう場合、
​
`using System.Collections.Generic;`
​
上記を定義する必要があるかと思います。
ご確認よろしくお願いいたします。
​
なお、恐れ入れますが、今回のエラーは弊社では再現できず、他の方からの報告がいただけていないので、お客様の特有実装や環境に原因があるかと思われます。
その場合、質問がありましたら、以下のユーザコミュニティがございますので、こちらのフォームをご活用くださいませ。
https://github.com/NIFCloud-mbaas/UserCommunity

**Comment by rise696** [comment]
using System.Collections.Generic;
​を定義した事でプログラム自体は動きましたがユーザーの取得はできませんでした「失敗＋e.Message」とも「ユーザー名＋user.UserName」ともどちらとも表示されませんでした

**Comment by ncmbadmin** [comment]
お返事いただき、ありがとうございます。
内容を確認いたしましたが、今回のエラーは弊社では再現できず、他の方からの報告がいただけていません。そのためお客様の特有実装や環境に原因があるかと思われ、恐れ入りますが、SDKの不具合ではないと判断させていただきます。

従って、申し訳ございませんが、本issueをclose致します。
SDKに関してのご質問などがございましたら、ぜひ以下のユーザコミュニティをご活用くださいませ。
https://github.com/NIFCloud-mbaas/UserCommunity

この度、フィードバックいただき、ありがとうございます。今後ともmobile backendどうぞよろしくお願いいたします。
