### ISSUE TITLE
Google Analytics SDKとの競合（Conflict） 

### ISSUE THREAD

**Issue by ys7809** [NIFCLOUD-mbaas/ncmb_unity#16]
Unity 5.3にNifty Cloud SDKを実装しプッシュ通知を利用したいのですが、以下のように、ビルド時に先に実装していたGoogle Analytics SDKとの競合エラーが発生してしまいます。

---

Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:\Program Files\Java\jdk1.8.0_40\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="D:/Android SDK\tools" -Dfile.encoding=UTF8 -jar "E:\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/internal/Command;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/internal/Command$1;
2 errors; aborting
## ]

Google Analytics SDKを削除してビルドすると、Nifty Cloud SDKがクラッシュし、Nifty Cloud SDKを削除すると、Google Analyticsは正常に動作するような状況です。

こちらのコミュニティやネットでも検索してみましたが、同様のケーススタディが見つかりませんでした。バグの可能性ありという指摘がありましたので、Issueを切ります。

**Comment by sensp** [comment]
■再現環境
・Unity: 5.3.4
・NCMB SDK: 2.1.1
・Unity向け Google アナリティクス プラグイン: googleanalyticsv3.unitypackage

■再現確認
・既存Unity向けNCMB SDKをインポートします。
・Unity向け Google アナリティクス プラグイン レポジトリから googleanalyticsv3.unitypackage をダウンロードし、Unity プロジェクトにインポートします。
　参照：https://developers.google.com/analytics/devguides/collection/unity/v3/devguide#prefab
  【インポートされるもの】
　①【Unity_Project】/Assets/Plugins/Android/　下記のファイル生成
		libGoogleAnalyticsServices.jar
    ②【Unity_Project】/Assets/Plugins/GoogleAnalyticsV3 フォルダ生成
    ③【Unity_Project】/Assets/Plugins/Editor フォルダ生成

・Build Settings -> Android ビルド実施 -> ビルドエラー発生再現
　　：：：：：
	stderr[
		Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/internal/Command;
		Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/analytics/internal/Command$1;
		2 errors; aborting
	]

■原因
 ・下記の同じクラスファイル存在で競合してエラー発生になります。
 ・<google-play-services.jar 中>
   google-play-services/com/google/android/gms/analytics/internal
  　Command.class
  　Command$1.class

 ・<Google アナリティクス(googleanalyticsv3.unitypackage)から生成：libGoogleAnalyticsServices.jar 中>
   libGoogleAnalyticsServices/com/google/android/gms/analytics/internal
  　Command.class
  　Command$1.class

■修正案1
 ・同じクラスが存在するので、google-play-services.jarにある下記の2個ファイルを削除・jar更新します。(ソフトWinRAR利用)
 　Command.class
 　Command$1.class

 ・libGoogleAnalyticsServices.jar ->ここの2個ファイルを削除するとGoogleアナリティクスが作動しません。

■修正案2
 ・Unity向け Google アナリティクス プラグイン googleanalyticsv3.unitypackage から googleanalyticsv4.unitypackageに更新することをおすすめします。
 ・参照：https://github.com/googleanalytics/google-analytics-plugin-for-unity/blob/master/GoogleAnalyticsV4.unitypackage

以上です。

**Comment by ncmbadmin** [comment]
issue投稿いただき、ありがとうございます。

Google Analytics SDKのすべてのバージョン互換性を持つことが難しいのため、
仕様として非対応とさせていただきます。
但し、今後ニーズが多くなった場合、対応検討する予定いたしますが、
一旦本issueをクローズさせていただきます。

今後ともmobile backendどうぞよろしくお願いいたします。
