### ISSUE TITLE
Android版アプリへのTargetSDK31対応

### ISSUE THREAD

**Issue by watanabe-tomoya** [NIFCLOUD-mbaas/ncmb_unity#226]
SDKの改善にご協力いただきありがとうございます。  
(Thank you for your support our SDK.)

SDKの不具合を報告する場合は、以下の項目を確認してください。  
(If you want to report a bug of the SDK, please confirm the following terms.)

- サンプルコードにAPIキーや個人情報が含まれていないか (The sample code does not include credential information?)
- 同じバグをすでに誰かが報告していてOpenになっているissueはないか (This bug is not being reported?)

## 不具合の概要(Description of bug)

- AndroidTargetSDKVersion31においてプッシュ通知が届かない事象が発生中

**Comment by ncmbadmin** [comment]
本件、以下のリリースで対応完了しまた。issueをクローズします。
https://github.com/NIFCLOUD-mbaas/ncmb_unity/releases/tag/v4.5.0
