### ISSUE TITLE
会員管理で再代入が必須な場合がありその理由が分からない

### ISSUE THREAD

**Issue by hounenhounen** [NIFCLOUD-mbaas/ncmb_unity#26]
下記の様なコードの場合コメントアウト部分の代入必須である理由が分からない

```
var acl = user.ACL
acl.SetRoleReadAccess(“Admin”,true);
user.ACL = acl;//この代入必須が分からない
user.SaveAsync();
```

**Comment by ncmbadmin** [comment]
お世話になっております、issue作成いただき、ありがとうございました。
本件他のお客様から現象報告がないこと、また不具合でないことからcloseとさせていただきます。
今後とも、mobile backend をどうぞよろしくお願いいたします。
