### ISSUE TITLE
UPM経由のインポート時のエラー

### ISSUE THREAD

**Issue by HIROHIRO1224** [NIFCLOUD-mbaas/ncmb_unity#273]
## 不具合の概要(Description of bug)

過去に.unitypackageファイルからインストールしていたのをやめ、UPM(Unity Package Manager)経由でインストールした際に画像のようなエラーが起動時とコンパイル完了時毎に表示される。

<img width="1081" alt="スクリーンショット 2023-08-24 19 48 42" src="https://github.com/NIFCLOUD-mbaas/ncmb_unity/assets/67212160/2266aaa1-2e52-4e26-af56-e2d8a0bc479a">

- SDKのバージョン: 5.1.1
- 不具合が発生した環境: Unity 2021.3.0f1 Macbook Air 2020 Late, MacOS Ventura 13.4.1

### 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)

1. unitypackageファイルから全てインポートする。
2. Assets/Editor,Plugin,NCMBのフォルダとファイル、Sceneフォルダ内のNCMB関連ファイルを削除
3. Unity editorのメニューバーのウィンドウ->パッケージマネージャーのプロジェクト内でプラスボタンを押してgit URLからパッケージを追加`https://github.com/NIFCLOUD-mbaas/ncmb_unity.git?path=/ncmb_unity/Assets`を入力し追加を押す
4. 完了すると上のエラーが出てきてその後コンパイル時と起動時にエラーが吐かれる。

**Comment by ncmbadmin** [comment]
お世話になっております。
検証を行ったところ、報告していただいたissueはSDKの不具合ではございませんでした。

今一度アプリでの設定を見直していただくか、mBaaSの有償テクニカルサポート、もしくはUser Communityにてご質問をお願いいたします。  
サポート： https://mbaas.nifcloud.com/support.htm  
User Community： https://github.com/NIFCLOUD-mbaas/UserCommunity

本issueはクローズいたします。
