### ISSUE TITLE
ビルドしたAPKをアンドロイド端末にインストールできない

### ISSUE THREAD

**Issue by kojioshima256** [NIFCloud-mbaas/ncmb_unity#30]
SDKのバージョン(SDK version)
2.2.0
不具合が発生した環境(Environment requirement)
unity5.3.5f1
不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
 unity5.3.5f1でAPKファイルをビルド後、アンドロイド端末にてインストールを行う。
エラーメッセージ(Error messages)
パッケージの解析中に問題が発生しました。

補足
SDKのバージョン2.0.0でビルドした場合は正常にインストールができます。

**Comment by ndyuya** [comment]
以下の条件にて再現確認を実施しましたが、
いずれの組み合わせの場合でも再現性が確認できておりません。

- 再現環境
  - Unity 5.3.5f1
  - NCMB Unity SDK
     - version 2.0.0 
     - version 2.2.0 
  - OSバージョン
     - Android 4.4 ～ 6.0

事象を再現させるための追加情報がございましたら、ご提供をお願いいたします。
（例：インストール時のAndroidのエラーログ、SDKで提供されている機能をどのように使用されているか、
　　　ソースコードのうちSDK利用箇所で開示可能な部分、他に使用されているライブラリ…など）

**Comment by ncmbadmin** [comment]
お世話になっております、issueを登録いただき、ありがとうございました。
以下の手順で再現確認いたしましたが、Unity SDK (v. 4.0.1)で再現されないことを確認いたしました。

* 確認の流れ
1.  Androidのアプリをビルドする
2. ビルドしたAPKをandroid端末に正常にインストールする

* 確認の環境
   - Unity 2019.1.0f2
   - ncmb_unity: 4.0.1
   - OS: android 8.0

従って、本issueはクローズさせていただきます。お手数かけますが、issueに記載した現象を改善するには最新版のSDKをご利用いただければと存じます。
今後とも、mobile backendどうぞよろしくお願いいたします。
