### ISSUE TITLE
Response Validationにチェックある場合、ダブルクォーテーション値を検索時NG

### ISSUE THREAD

**Issue by sensp** [NIFCloud-mbaas/ncmb_unity#38]
■現象
1. Script用のサーバstubを立ち上げる。(あるいは、node.jsを立ち上げる)
2.UnityEditorTestを実行すると、テスト失敗(NG)になっている。
※NCMBObjectTest.cs
          |-- doubleQuotationUnescapeTest()
       NG内容 ="Authentication error by response signature incorrect."

・チケット: Unity No.122592と同じ課題です
- 事前環境設定：Response Validationにチェックをする
- 値にダブルクォーテーションが入っている場合 - 登録、更新、削除はOK, 検索はNG -> レスポンスシグネチャCheckにNGになる

■原因
 v1.1.5 :/ncmb_unity/releases/
   ・データに絵文字が含まれる場合のレスポンスシグネチャ計算の不具合を修正しました
　　 -> ダブルクォーテーションが検索出来ない不具合発生する結果になった！

 v2.1.1 :/ncmb_unity/releases/
   ・ダブルクォーテーションがフィールド内に含まれた場合にデータを検索出来ない不具合を修正 
　　-> 正しく修正出来てない！

■対応
・今回の修正で過去のv1.1.5とv2.1.1の両方対応にも合う修正する
 ・パターン１ : ダブルクォーテーションなどエスケープがあるデータ
 ・パターン２ : 絵文字(4桁の16進数で表記されたUnicode文字)があるデータ
     (絵文字一覧 : http://www13.plala.or.jp/bigdata/emoji.html)
 ・パターン３ : 絵文字とダブルクォーテーションが混雑するデータ

**Comment by ykokw** [comment]
このissue内容は

ダブルクォーテーションを含むデータを検索した場合に、レスポンスシグネチャの検証がNGになる

ということでしょうか。
レスポンスシグネチャの検証をしない場合はダブルクォーテーションを含んでいても検索可能であれば
状況を整理したうえで、issueのタイトルを修正していただけますでしょうか。

**Comment by sensp** [comment]
このissue内容
1.Response Validationにチェックない場合
 - ブルクォーテーションを含むデータを検索した場合、異常ありません。

2.Response Validationにチェックある場合
 - ダブルクォーテーションを含むデータを検索した場合、レスポンスシグネチャの検証がNGになります。

**Comment by ncmbadmin** [comment]
issueの登録、ありがとうございました。
本件は対応完了しましたので、issueをクローズさせていただきます。
