### ISSUE TITLE
UnityPlayerProxyActivity が非推奨

### ISSUE THREAD

**Issue by gs0zk1** [NIFCLOUD-mbaas/ncmb_unity#72]
- [release note of v5.4](https://unity3d.com/jp/unity/whats-new/unity-5.4.0)
- Android: UnityPlayerNativeActivity と `UnityPlayerProxyActivity` が非推奨に
非推奨となったライブラリを利用するところを更新必要

**Comment by kobayashi-masaya** [comment]
ダイアログPushの確認のため、Android 9以下での確認が必要。
