### ISSUE TITLE
リッチプッシュのウィンドウ上で PDFファイルのURLを表示することができない

### ISSUE THREAD

**Issue by vfa-duyna** [NIFCLOUD-mbaas/ncmb_unity#84]
## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version)
3.1.0
- 不具合が発生した環境(Environment requirement)
Android 6
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
以下のURLを指定したリッチプッシュを送付する。 
　パターン①：PDFファイル 
　パターン②：通常のWebページ 
- 事象 (Phenomenon)
　パターン①：画面がホワイトアウトして、PDFが表示できない 
　パターン②：通常のWebページは表示できるが、そのWebページからリンクしているPDFファイルが開けない。

**Comment by ncmbadmin** [comment]
以下のissue対応されたAndroid SDKバージョンを更新されたため、本issueも解消されましたので、クローズします。
https://github.com/NIFCLOUD-mbaas/ncmb_android/issues/135
